<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Authors>MlsMoon</Authors>
    <Company>MlsMoon</Company>
    <Product>Moon Game Dev Tool Manager</Product>
    <Copyright>Copyright (c) 2026 MlsMoon</Copyright>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/MlsMoon/moon-game-dev-tool-manager</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Version Condition="Exists('$(MSBuildThisFileDirectory)VERSION')">$([System.IO.File]::ReadAllText('$(MSBuildThisFileDirectory)VERSION').Trim())</Version>
    <Version Condition="'$(Version)' == ''">0.1.0</Version>
    <InformationalVersion>$(Version)</InformationalVersion>
  </PropertyGroup>
</Project>
